#!/usr/bin/env bash
# Bash script that configures an ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
sudo bash -c 'echo "server {
	listen 80 default_server;
	server_name _;

	location / {
	root /usr/share/nginx/html;
	}
}" > /etc/nginx/sites-available/default'
