#!/usr/bin/env bash
# Bash script that configures an ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo ngnix start
