#!/usr/bin/env bash
# Permanent redirect

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/\blisten 80\b/listen 80 default_server/' /etc/nginx/sites-available/default
echo -e "location /redirect_me {\n	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}" | sudo tee -a /etc/nginx/sites-available/default
sudo service nginx restart
