#!/usr/bin/env bash
#bash script that gives information about a file
filename=school
if [ -e $filename ]; then
echo "school file exists"
if [ -f $filename ]; then
echo "school is a regular file"
fi
if [ -s $filename ]; then
echo "school file is not empty"
else 
echo "school file is empty"
fi
else
echo "school file does not exist"
fi
