#!/usr/bin/env bash
#configures an ubuntu server
if [ "$EUID" -ne 0 ]; then
	exit 1
fi
cp /etc/hosts /etc/hosts.bak

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

cat /etc/hosts
